apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster002-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    events {
      worker_connections  10240;
    }

    error_log /var/log/nginx/error.log error;

    http {
      proxy_ssl_certificate         /ssl/client01.crt;
      proxy_ssl_certificate_key     /ssl/client01.key;

      map $remote_addr $lb { 
        default a3b3fe5e3bea948518743c037d9da8ca-2c1045bde07de312.elb.eu-central-1.amazonaws.com;
      }

      resolver 169.254.20.10 valid=30s ipv6=off;

      server {
        listen 80;
        location / {
          proxy_pass https://$lb:20000;
          proxy_set_header Host $host;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster002
spec:
  selector:
    matchLabels:
      app: cluster002
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster002
        component: client
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-config
        - mountPath: /ssl
          readOnly: true
          name: nginx-certs
      volumes:
      - name: nginx-config
        configMap:
          name: cluster002-config
      - name: nginx-certs
        configMap:
          name: cluster002-certs
---
apiVersion: v1
kind: Service
metadata:
  name: cluster002
  labels:
    app: cluster002
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 80
    protocol: TCP
  selector:
    app: cluster002