version: "3.7"
services:
  master:
    image: nginx:1.17
    volumes:
    - ./ssl:/ssl:ro
    - ./master.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 30000:30000
    - 20000:20000
  slave:
    image: nginx:1.17
    volumes:
    - ./ssl:/ssl:ro
    - ./slave.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 4444:80
    # streams
    - 4445:81
  test:
    image: solsson/http-echo
  test-mysql:
    image: percona:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=12345678
  test-ssl:
    image: nginx:1.17
    volumes:
    - ./ssl:/ssl:ro
    - ./test-ssl.conf:/etc/nginx/nginx.conf:ro