apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      errors
      health

      # ec2 fix
      rewrite stop name regex ^(ip-\d{1,3}-\d{1,3}-\d{1,3}-\d{1,3}\.ec2\.internal) {1}
      rewrite stop name regex .*\.ec2\.internal ec2.internal.invalid

      # service mesh
      rewrite stop name regex .*\.cluster([0-9]+) cluster{1}.default.svc.cluster.local
      rewrite stop name regex .*\.global cluster-global.default.svc.cluster.local

      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
      }

      prometheus :9153
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }