apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-certs
data:
  {{- $files := .Files }}
  {{- range tuple "client01.crt" "client01.key" }}
  {{ . }}: |- {{ . | printf "ssl/%s" | $files.Get | nindent 4 }}
  {{- end }}