apiVersion: v1
kind: ConfigMap
metadata:
  name: master-certs
data:
  {{- $files := .Files }}
  {{- range tuple "server.crt" "server.key" "ca.crt" }}
  {{ . }}: |- {{ . | printf "ssl/%s" | $files.Get | nindent 4 }}
  {{- end }}